# Fuente
font_family      JetBrainsMono Nerd Font
font_size        11.0

# Remote control (necesario para que apply_wal pueda hacer set-colors en vivo)
allow_remote_control yes
listen_on unix:/tmp/kitty

# Colores dinámicos de pywal
include ~/.cache/wal/colors-kitty.conf
